#!/usr/bin/python
#
# Validate data for the pundit archiver
#

import pscheduler

try:
    json = pscheduler.json_load()
except ValueError as ex:
    pscheduler.succeed_json({
        "valid": False,
        "error": str(ex)
        })

# Set the data validator
# Everything is optional so we can't use it right now
data_validator = {
    
    "type": "object",
    "properties": {
        },
    "additionalProperties": True
}

# validate against the data
valid, error = pscheduler.json_validate(json, data_validator)

if not valid:
    pscheduler.succeed_json({
        "valid": False,
        "error": error
        })
    
pscheduler.succeed_json({ "valid": True })
